/** fnreq.h ******************************************************************/
/*                                                                           */
/* A module that opens and handles a file name requester.                    */
/*                                                                           */
/*                                                                           */
/*****************************************************************************/

/* Error values returned :*/
#define	FN_OK		0
#define FN_Cancel 	1
#define FN_NoSuchDrawer 2
