#include <exec\types.h>
#include <exec\nodes.h> 
#include <exec\lists.h>
#include <exec\interrupts.h>
#include <exec\memory.h>
#include <exec\tasks.h>
#include <exec\ports.h>
#include <exec\libraries.h>
#include <exec\io.h>
#include <exec\devices.h>
#include <clib\macros.h>
#include <devices\timer.h>
#include <librarie\dos.h>
#include <graphics\gfx.h>
#include <hardware\blit.h>
#include <graphics\copper.h>
#include <graphics\display.h>
#include <graphics\gels.h>
#include <graphics\regions.h>
#include <graphics\clip.h>
#include <graphics\rastport.h>
#include <graphics\view.h>
#include <graphics\gfxbase.h>
#include <graphics\text.h>
#include <graphics\gfxmacros.h>
#include <graphics\layers.h>
#include <intuition\intuition.h>
#include <devices\inputevent.h>
#include <devices\keymap.h>
#include <workbench\startup.h>




